---
- hosts: rundeck
  become: yes
  remote_user: ubuntu
  tasks:
  - name: Mount disk
    command: mkfs.xfs /dev/nvme1n1
  - name: Create dir rundeck
    command: mkdir /rundeck
  - name: Mount rundeck
    mount:
      path: /dev/nvme1n1
      src:  /rundeck
      fstype: xfs
      opts: defaults
      state: present
  - name: Permissao para rundeck
    command: chown ubuntu:ubuntu /rundeck
  - name: Download script docker
    get_url:
      url: https://get.docker.com
      dest: /tmp/docker.sh
      mode: '777'
  - name: Install docker
    command: bash /tmp/docker.sh
  - name: Install rundeck
    command: docker run -d --name some-rundeck -p 4440:4440 -v /rundeck:/home/rundeck/server/data rundeck/rundeck:3.3.10